build:
    stage: build
    image: docker:19.03.12

    services:
        - docker:19.03.12-dind

    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY  

    script:
        - docker build --build-arg COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}${CI_PIPELINE_ID} -t ${CI_DOCKER_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}${CI_PIPELINE_ID} -t ${CI_DOCKER_REGISTRY_IMAGE}:latest .
        - docker push ${CI_DOCKER_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}${CI_PIPELINE_ID}
        - docker push ${CI_DOCKER_REGISTRY_IMAGE}:latest
    only:
      refs:
        - dev
        - qa
    except:
      - merge_requests

deploy:
    stage: deploy
    before_script:
        - 'which ssh-agent || ( apt-get update -qy && apt-get install openssh-client -qqy )'
        - eval `ssh-agent -s`
        - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null # add ssh ke
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh        
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - git config --global user.email "devops@mirantis.com"
        - git config --global user.name "Mirantis DevOps"

    script:
        - git clone ${CI_ARGOCD_GIT_REPO}
        - cd argocd-autopilot-app
        - >
           sed -i "s/newTag.*/newTag: \"${CI_COMMIT_SHORT_SHA}${CI_PIPELINE_ID}\"/" apps/hello-world/overlays/${CI_COMMIT_REF_NAME}/kustomization.yaml
        - git add apps/hello-world/overlays/${CI_COMMIT_REF_NAME}/kustomization.yaml
        - git commit -m "updated dev tag to ${CI_COMMIT_SHORT_SHA}${CI_PIPELINE_ID}"
        - git remote add github ${CI_ARGOCD_GIT_REPO}
        - git push github main
    only:
      refs:
        - dev
        - qa
    except:
      - merge_requests